# Generated by Django 3.1.7 on 2021-04-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=245)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(default=0)),
                ('response_time', models.IntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.jpg', upload_to='avatars')),
                ('autograph', models.ImageField(blank=True, default='autographs/default.jpg', upload_to='autographs')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'signer',
                'verbose_name_plural': 'signers',
                'ordering': ['-created_at'],
            },
        ),
    ]
