# Generated by Django 3.1.7 on 2021-04-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210421_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSig_Signer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groupsig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groupsig')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.signer')),
            ],
        ),
        migrations.AddField(
            model_name='groupsig',
            name='signers',
            field=models.ManyToManyField(blank=True, related_name='groups', through='api.GroupSig_Signer', to='api.Signer'),
        ),
    ]
