# Generated by Django 3.1.7 on 2021-04-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210423_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='groupsigs',
            field=models.ManyToManyField(blank=True, related_name='categories', to='api.GroupSig'),
        ),
    ]
