# Generated by Django 3.1.7 on 2021-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category_groupsigs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='groupsig',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
