# Generated by Django 3.1.7 on 2021-05-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210427_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.jpg', upload_to='avatars')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('price', models.FloatField(default=0)),
                ('max_requests', models.IntegerField(default=10)),
                ('num_requests', models.IntegerField(default=0)),
                ('charity_percent', models.IntegerField(default=0)),
                ('total_raised', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.charity')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.signer')),
            ],
            options={
                'verbose_name': 'drop',
                'verbose_name_plural': 'drops',
                'ordering': ['starts_at'],
            },
        ),
    ]
