# Generated by Django 3.1.7 on 2021-05-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_charity_drop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'ordering': ['name'], 'verbose_name': 'charity', 'verbose_name_plural': 'charities'},
        ),
        migrations.AddField(
            model_name='charity',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, default='backgrounds/default.jpg', upload_to='backgrounds'),
        ),
        migrations.AddField(
            model_name='request',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
